services:
  mongodb:
    image: mongo:7.0
    container_name: contract_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: contract_intelligence
    volumes:
      - mongodb_data:/data/db
    networks:
      - contract_network

  backend:
    build: ./backend
    container_name: contract_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password@mongodb:27017/contract_intelligence?authSource=admin
      DEBUG: "True"
      LOG_LEVEL: INFO
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - contract_network

  frontend:
    build: ./frontend
    container_name: contract_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - contract_network

volumes:
  mongodb_data:

networks:
  contract_network:
    driver: bridge
