services:
  backend:
    build: ./backend
    container_name: contract_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DEBUG: ${DEBUG:-True}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app
    # depends_on:
    #   - mongodb  # Using MongoDB Atlas instead
    networks:
      - contract_network

  frontend:
    build: ./frontend
    container_name: contract_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - contract_network

volumes:
  mongodb_data:

networks:
  contract_network:
    driver: bridge
